/* 
 * QR code generator library (.NET)
 *
 * Copyright (c) Manuel Bleichenbacher (MIT License)
 * https://github.com/manuelbl/QrCodeGenerator
 * Copyright (c) Project Nayuki (MIT License)
 * https://www.nayuki.io/page/qr-code-generator-library
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

using System.Collections;
using System.Collections.Generic;
using static Net.Codecrete.QrCodeGenerator.QrCode;

namespace Net.Codecrete.QrCodeGenerator.Test
{
    public class QrCodeDataProvider : IEnumerable<object[]>
    {
        private static readonly List<QrSegment> Segment1 = QrSegment.MakeSegments("A");
        private static readonly string[] Modules1 = {
            "XXXXXXX   XX  XXXXXXX",
            "X     X X   X X     X",
            "X XXX X   XXX X XXX X",
            "X XXX X   XX  X XXX X",
            "X XXX X  X  X X XXX X",
            "X     X X   X X     X",
            "XXXXXXX X X X XXXXXXX",
            "        XXXX         ",
            "    XXXX      XX   X ",
            " XXX   XX   X  X X XX",
            "  X  XX  X XX XXXXX  ",
            "X  XXX X XX  X  X X  ",
            " X X  XX XX X     X X",
            "        X  XX     X X",
            "XXXXXXX XX  X X     X",
            "X     X X  X  XX X   ",
            "X XXX X XX     XXXXXX",
            "X XXX X   XXX  X X XX",
            "X XXX X  XX    XXXX  ",
            "X     X  X XX   X X X",
            "XXXXXXX  XX XXX   XXX"
        };

        private static readonly List<QrSegment> Segment2 = QrSegment.MakeSegments("Hello, world!");
        private static readonly string[] Modules2 = {
            "XXXXXXX     X XXXXXXX",
            "X     X  X X  X     X",
            "X XXX X X XXX X XXX X",
            "X XXX X X     X XXX X",
            "X XXX X XX  X X XXX X",
            "X     X XXXX  X     X",
            "XXXXXXX X X X XXXXXXX",
            "        X X          ",
            "X XXXXX  XXX  XXXXX  ",
            "   XX  XX   XX  XXX X",
            "   X  X XXX XXX  XXX ",
            " XX  X X  XXXX X XX  ",
            "XX XXXX X   X XX    X",
            "        X    XXXXX   ",
            "XXXXXXX  XX XXXX  XX ",
            "X     X X X XX X XXX ",
            "X XXX X XX XXXX X  XX",
            "X XXX X X X    XXX   ",
            "X XXX X XXXXX XX  X  ",
            "X     X   X XX  XXX  ",
            "XXXXXXX XX X  X X  X "
        };

        private static readonly List<QrSegment> Segment3 = QrSegment.MakeSegments("The quick brown fox jumps over the lazy dog");
        private static readonly string[] Modules3 = {
            "XXXXXXX XXX  XX    XXXXX  XXXXXXX",
            "X     X  X  X XX  X  X    X     X",
            "X XXX X    XX XX   X XXX  X XXX X",
            "X XXX X   XX   XX XX  XXX X XXX X",
            "X XXX X X XX  X     XXXX  X XXX X",
            "X     X X  XX  X   X  X X X     X",
            "XXXXXXX X X X X X X X X X XXXXXXX",
            "         X X X     XXXX          ",
            " XXXXXXX         X X  XXX  XX   X",
            "X  X   XX    XXX XXXX  X  X     X",
            " X  X X    X    XX      X     X  ",
            "XXX  X  XXXX XX  XX  X XX  XXXXXX",
            " X X XX   XXX   X     X XX XX    ",
            "XX X   X XX XX  X X   XX XXX  X X",
            " XX  XX X    X  X   X X X  XX XX ",
            "X X    X XXX XX  X XXX  XXXX XX  ",
            " XXXX XX X X  X X        X XX  X ",
            "XXX  X      XX   X X   X  X  XXXX",
            "X     XX X X X    X  X  XX   XXX ",
            "XXXX     XX     X    XXXX     X  ",
            "   XXXX X X X  X  XX    XX  X    ",
            "XX  X    XX  XXXX XXXX XX X  X X ",
            "X X   XX X  X    X  XX    X  X X ",
            "X  XXX X  XX XX  XXXXX   XX  XXXX",
            "X  XX XX  XX  XXX XXX X XXXXXX  X",
            "        XXXXXX  X  XXX  X   X XXX",
            "XXXXXXX X   X  X    XX XX X X XX ",
            "X     X XX    X X  XXX XX   XXXX ",
            "X XXX X X   XX X  XX  X XXXXXX XX",
            "X XXX X XXX XXXXXX XXX  X   XXX X",
            "X XXX X X X  X X XX   X X X      ",
            "X     X XXX  X   X  XX    X  XX  ",
            "XXXXXXX   X   X XX    XXX  X   X "
        };

        private static readonly List<QrSegment> Segment4 = QrSegment.MakeSegments("87634846443833526");
        private static readonly string[] Modules4 = {
            "XXXXXXX  X    XXXXXXX",
            "X     X X  X  X     X",
            "X XXX X XX  X X XXX X",
            "X XXX X X XX  X XXX X",
            "X XXX X X X X X XXX X",
            "X     X X XX  X     X",
            "XXXXXXX X X X XXXXXXX",
            "          XX         ",
            "  X  XXXX X XX XXXXX ",
            " X   X XX  X XX  X   ",
            " XXXX X  X X XX X X  ",
            "X  XX  X X X  XXXX  X",
            "XXXX  X    XX  XX   X",
            "        X     XXX  XX",
            "XXXXXXX X  XX     X X",
            "X     X XX X  X  XX  ",
            "X XXX X  XXXX   X X X",
            "X XXX X  XXXXX X     ",
            "X XXX X XX XX XX XXXX",
            "X     X  XX XXXX X X ",
            "XXXXXXX  XXXX X  X XX"
        };

        private static readonly List<QrSegment> Segment5 = QrSegment.MakeSegments("kVtnmdZMDB wbhQ4Y0L0D 6dxWYgeDO7 6XEq8JBGFD dbA5ruetw0 zIevtZZkJL UnEcrObNuS COOscwe4PD PL2lKGcbqk uXnmfUX00E l4FsUfvkiU O8bje4GTce  C85HiEHDha EoObmX7Hef VEipzaCPV7 XpBy5cgYRZ VzlrmMTRSW f0U7Dt0x5j Mb5uk2JcA6 MFov2hnHQR");
        private static readonly string[] Modules5 = {
            "XXXXXXX XXXXX X  XX  X    X    XXX    X XXX  X  X  XX XXXXXXX",
            "X     X    XX  XXXXX XX XXXX     X  XX  XXX XXX  X XX X     X",
            "X XXX X  X  X   XXXXX  XX  XX   XXX X   XX XXX  X XXX X XXX X",
            "X XXX X XX X  X   X  X XXX   X XX XX X  X    XX  XX X X XXX X",
            "X XXX X X   X XX X  XX X X XXXXXX  X XXXX X  X    XX  X XXX X",
            "X     X XXXX   XXX  XX XX X X   XX  X XX XX  X XXXX   X     X",
            "XXXXXXX X X X X X X X X X X X X X X X X X X X X X X X XXXXXXX",
            "        X  X XXXXX  XXX  XXXX   X XXXX XXX    XXX   X        ",
            "X   X XXX XXX XXXXX       X XXXXX XXX  X  X X   XX   XXXXX  X",
            "XXXX      X X            X    X XX X  X   XX X  XXXX XXXX X  ",
            " X XX X  X X  X  X  XXXX X XXX X  X   XXX X   X X X X X  XX  ",
            "X  XXX X XX      X XXX   X  X     X X  X  X XXX XX XXXX X XX ",
            "XX X XXX  XXXXXXX XX  XXX X   XXXX  X  X X XX   XXX X X X X  ",
            "X X    X XXXX     X X   XX     XX   X XX XXXXX XX XX  X XX   ",
            "  X   XX  XX X  XXXX  XXX XXXX X   X   X XXX  XX X XX XXX X  ",
            "X XX     X  XXXX  X     X   X  X X X X XXXX   XX XXXX     X  ",
            "XX  X X   XXX X XX      XXXXX X X  X XXXX X   XXXXXXXXX X XXX",
            "X      X XXXXX  XX XXX  X   XXX X     X XXXX X   XXX XX   X  ",
            "X XXX XX XXX X XX  XXX   XXX   X    X X  XXXXX  XXXX XX      ",
            "XX  X  X       XX     XXX XXXX   XX  XX  XX XXX     XX    XX ",
            "  XXX X X X X X  X  X  XX    X XXXXXXXXX XX X  XX    XX XX X ",
            "X X    X X    X XXX XXX XXXX  XXXX  X X XXX  X  X XX  XX X X ",
            "   XX X  X   XXX    XXXXXX XX  X  X  XX X    XXX X XX XX  X  ",
            " XX X  XXXX X  XX X X  XX    X     X XXXX X  XXXXXX X  X  X  ",
            "XX    XXXX X  XXX    XX X X XXXX  XXXX X    XX XX     X XXXXX",
            " X XX    XXXXXXXXXXX XXX X XX X XXX X    X XXX XX XX XX XXX X",
            "XXXXX X      X X XXX X XX    XX  XXX    XX    X  XX X  X X   ",
            "X   X  X    X X  X X  X XXXXX  X X  XX X   XXX X     XX X X X",
            " X XXXXXX     X  XXX  X   X XXXXX  XX X     XX XXXX XXXXX XXX",
            "  XXX   X   XXX  XX XX XXX  X   XX X  XXXXX       XXX   XX XX",
            "XXXXX X X  X X XX XX X   XX X X XXXX   XXXX    XXXX X X X X  ",
            "  X X   X  XX X X     X XXXXX   X XXXXX XX    X   XXX   X X  ",
            "   XXXXXX XX XXXXX     XX X XXXXX   X  X    XX XXX  XXXXX XXX",
            "X X  X  X XX  X X   X  XXXXX  XXXX X  XXXXXXXX  X XX   XX XX ",
            "    X XXXXX X XXXXX   X  X X  XXX X     XX   X XXX  X        ",
            "X  XXX  X XXX X XXXXX X XX XXX    X     XX X X XXX  XX   XXXX",
            " XX X XX X X XXXXXXX XX   X   XX X  X      XXXXXXXX X XX XX X",
            "XX X   X XX  X  X X     XX  XX  XX XX XX XX XX  X X X X XX XX",
            " X XX X X XXXXX  XXX XX X  XX    XXX  XXXXX  X XX  X X  XX  X",
            "XX  X    XX    XXXXX   XXX X X X  X     XX  XXXXX     XXX XX ",
            "    XXXX   X  XX XXX  XXXXXX XX XXXXXX X    X X XXX X  X XX X",
            "XXXX X    XX XXX  X XXX X X X  X   XX X  XX XX X  X XXX XX X ",
            " XXXXXX     XXX X XX  X    XX   XX  X XXX  X     X XX   XXXX ",
            "  XXXX     XXX   XX  XXX  X   X  XXXX    X  XXX  X X  X X XXX",
            "  XX XXXX   X X  X X XX X X XXXXXX  X X  XXXX XXXX  XXX XXX X",
            "XX  XX  XXX    XX   XXXXXXX   X X   XXXX  X X  X XX X   XXXX ",
            " XX  XXX X XXXX X  X   X   X  XXX XX X  X  X XXX XX XX    XX ",
            "  XX X X XXX  XXXX   X X  XXXXX   XXXX  X   XXXX X X XX   XX ",
            "XXX   XX X  XX XXXX       X XX  XX XXXXX  X X  XX       X X  ",
            "XX XX    X XX XXXX X X XX  XX XXXX X  XX XX XX X  X     XX X ",
            "  XXXXXX X X     XXXX  XXXXXX      X    X XX XXXX XX    XX   ",
            "XXX X  XXX X  XX  XX  XX XXX  XXXXX XXX X XXX  XX X  X X XXX ",
            "XXXX  XXX    XXX  X   X   X XXXXX   X  X   XX XXXX  XXXXX X X",
            "        XXXX XXXX X XXXXXX  X   XX X  X  XXXXX    X X   X  X ",
            "XXXXXXX X   X XXX X X X   X X X XXX XXXX  XXXXXX  XXX X XX   ",
            "X     X  XX XX   XXXXX X  X X   XX X X XXXX  X XXX XX   X X  ",
            "X XXX X X   X  XX  X  XX XX XXXXX  X  XXX    X XXX  XXXXX  XX",
            "X XXX X   X X XX     XX XX   XXX X   XX XXXX X    X      X  X",
            "X XXX X     X  X  X XX   XXX X XXX  X X  XXXX XX XX X    XXX ",
            "X     X   X XXX X   XXXX  XX X  XXXX XXX XXXXX  XX XX  XX XX ",
            "XXXXXXX X    X  X    X  X  X    X  XX X    XXX  XX      X XXX"
        };

        private static readonly List<QrSegment> Segment6 = QrSegment.MakeSegments("😀 € éñ 💩");
        private static readonly string[] Modules6 = {
            "XXXXXXX           XX  XXXXXXX",
            "X     X      XX   X X X     X",
            "X XXX X XX X  XX X  X X XXX X",
            "X XXX X XX     X   XX X XXX X",
            "X XXX X  XXXX X XXXXX X XXX X",
            "X     X  X X XX XXXXX X     X",
            "XXXXXXX X X X X X X X XXXXXXX",
            "            XX      X        ",
            "   XX XX   XXX  X XXX    XX  ",
            " X XX  X XXX  X     X X X XXX",
            "X    XX X XX XXXXXX  X  X XXX",
            "  XXXX XX XX   XXX     X XX X",
            "X XX  XXXX   X XXX XXX X   XX",
            "X  XXX  X   X X   XX   X    X",
            " X X  XX   X X XX X     X XXX",
            "X X     X XXX XX    X   X  XX",
            "X XXXXXXX        XX X XX XXX ",
            "XX   X X  XXXXXXX X X XX   X ",
            "XXXX XXXX  XXXXX XX XXXX XX  ",
            "XX  X  XXXXX XX       X XX  X",
            "XX X XX   X  X XXX  XXXXX  XX",
            "        XX  XXXX  X X   X  X ",
            "XXXXXXX XXXXX X  X XX X X XXX",
            "X     X      X X    X   X XX ",
            "X XXX X X   XXX   XXXXXXXXXXX",
            "X XXX X XXXXXXXXXX XX X    X ",
            "X XXX X   XXX X XX  XX  X XXX",
            "X     X   XXXXX  XXXX X X   X",
            "XXXXXXX    XX  X X  X  XXXX  "
        };

        private static readonly List<QrSegment> Segment7 = QrSegment.MakeSegments("DOLLAR-AMOUNT:$39.87 PERCENTAGE:100.00% OPERATIONS:+-*/");
        private static readonly string[] Modules7 = {
            "XXXXXXX XXX XX X XXXX XXXXXXX",
            "X     X      XXXXX  X X     X",
            "X XXX X X XX X XX XXX X XXX X",
            "X XXX X  XXX X X  X X X XXX X",
            "X XXX X  XX   XX X X  X XXX X",
            "X     X XX X X XX   X X     X",
            "XXXXXXX X X X X X X X XXXXXXX",
            "          XXX XXX            ",
            "X X   XX X  XXX  X  X  X  X X",
            " X      X XXXX XX X XXXXXX XX",
            "   XX X  X  X  XXX X XX     X",
            "  X X    X XXX X   XX X XX   ",
            "X  XX X    XXX XXXXXX   X    ",
            "  X  X    XXX   X    X    X  ",
            " XX XXX  XXX XXX XXX   X  XX ",
            "       X  XXX X     XXX  XXXX",
            " X XXXXXXXX  XXXX XXXX XX   X",
            "   X X X   X XXX  X  X X  XX ",
            "XX   XXXX   X       XX     XX",
            "  X X    XXXXX  XX X XXX XX X",
            "XXX XXX X X  X   XX XXXXX   X",
            "        XX     XX X X   XX  X",
            "XXXXXXX XXX XXXX X  X X XX X ",
            "X     X   X   XXX   X   X XXX",
            "X XXX X  XXX XXXXX XXXXXXX X ",
            "X XXX X  XX X XX  X XX X  XX ",
            "X XXX X X  X X XXXXX  XXX  XX",
            "X     X  XX X  X  X  X X  X X",
            "XXXXXXX XXX XXXX X X XX X  XX"
        };

        private static readonly List<QrSegment> Segment8 = QrSegment.MakeSegments("こんにちwa、世界！ αβγδ");
        private static readonly string[] Modules8 = {
            "XXXXXXX  X    X  X XXXX   XXXXXXX",
            "X     X X    X  X X       X     X",
            "X XXX X  XX X  X    XX X  X XXX X",
            "X XXX X X XX  XXX X X X X X XXX X",
            "X XXX X X  XXXXXXX   XXX  X XXX X",
            "X     X   XXXX XXX X  X X X     X",
            "XXXXXXX X X X X X X X X X XXXXXXX",
            "        X   X  XXX   XXX         ",
            " X XXXX XXX  X XX X    X XX XX X ",
            "     X  X XX  X  XXX XXX  X   X X",
            "X XXXXX XXXX XXX   XX XX  X X X  ",
            "X X X  X X  XX    XXXXXXX X XX   ",
            " XXX  XX XX  X XXX X X XX     X  ",
            "X  XX  X X X   XXXXXX   XXX X XXX",
            "X  X XX  XX XXXX  XXX X XX X XXXX",
            "XXXX   X   X XXX  X XX   XXX  XX ",
            "  X  XX X  X  X XXX  X XX  XXX  X",
            "XX X    XX  X X X     X X XX XXXX",
            "      XXX  X        XXX        X ",
            "XXX     XX    XXXXXXX X XX   X   ",
            "   X  XXX   X   XX   XX  XXXX   X",
            "XXX X  X XXXXX         XXX X  X  ",
            "X     XX XXX XXXX  XXX  X    XXX ",
            "X X    XXX  X      XXXX  XX X  XX",
            "XXX X X X X X    XX  XX XXXXXXXXX",
            "        X X   XX XX XX  X   X XX ",
            "XXXXXXX  X  XXX X       X X XX  X",
            "X     X XX  X   XX   XX X   X   X",
            "X XXX X XX X XX XXX  XX XXXXXXXX ",
            "X XXX X X XXX X   X   X  XXXX   X",
            "X XXX X       XXXX X XXXXX X X XX",
            "X     X XXX  X X XXXXXX XXX X  XX",
            "XXXXXXX  X  X X X XX   X  XXXX   "
        };

        private static readonly List<QrSegment> Segment9 = QrSegment.MakeSegments("Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, 'and what is the use of a book,' thought Alice 'without pictures or conversations?' So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her.");
        private static readonly string[] Modules9 = {
            "XXXXXXX X X XX X  XXX X XX X X X X  X   XXXX X  X XX   X  XX XXXXXX  XX  X     XXX  X XX  X    XX    XXX XX X XX  XXXXXXX",
            "X     X X   XXX   X    XX X   X  XXXX X  XXXX   XX XX  X  X X  XXXX  XX  XX  XX      X XXXX XX     XXXXXX    XX X X     X",
            "X XXX X XXX X      X XX X         X  XXXXX X   XXXXX    X XX X X X  XXXX  XX      XXX X      XX X X  X X XX X  XX X XXX X",
            "X XXX X   XX       XX  X   XXX  X X   XXX X   XXX   X X X X   XXXXXXX  XXXXXXXX XX X   X  XXXXX       XX XXX XXXX X XXX X",
            "X XXX X   X XXX    XXXX XXX XXXXX XXX X X XXXX X XX X XXXXXXXX        X XX X  XXXX XXXXXXX    XX   X  XX   XX  X  X XXX X",
            "X     X XX XX  XX X      XXXX   X   X XX  X X  X  X    XX   XX  X XXX  XX     XXX   X   X X XX   X  XXX XX   XXX  X     X",
            "XXXXXXX X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X XXXXXXX",
            "        X      XXX       X  X   X X    X XX X  XXX  X XXX   XX X X XX X    X   X  XXX   X  X XXXX X  X   XXXXXXXX        ",
            "  XXX X X XX  X  XX  XX X X XXXXXX   X  X  XXX  X    X  XXXXX    X XX X  X X  X    XXXXXXXXX X  XXX   XX   XXXX  XXX  XXX",
            "  XXXX     XXX  XXXXX   XX      X  X  X XX X  X   XX XXX  XXXXXX XX  XX  X  X     XXX  XXXX XXXXX X  XXX X   XX X X XX   ",
            "XX X XXX X   X XX     XXX   X XX XXX  X XXX XX    X   X X       X XX   XX X  XXXX    X XXXX X  X   XXXX X    X    XX   XX",
            " X XXX XXXXX   X X   XXX X  XX X XX XXXX XX  XX   XX XX XXX X X XXX XX XX XXX  X XX XXX    X  XXX X  X X XXXX XXXXXXX   X",
            "X   XXXXXX  X   XXX XX X  XX  XXXXXXX  XXXXXXX XXXXX X X X X XX  XX X XXXX  XX X X    X   X XX  X XX  X  X  XXX    XXXX  ",
            "XX XXX  XX   XXXX X XXXXX   XX  XXX  XXX   XX XX     X X XX XX XXXX   XX XXXX   XX XXX XX X     XX X XX XX X XX XX  XX X ",
            "XX   XXXX  X X XX XXXXX XXX X    XXX XXXXX  X XXX XXXXX X  XXXXXX      X  XX X  X  XXX XXXX X  X X XX X X       X      XX",
            "X   XX XXX   X     XX  XX X   XXXXXXX X  XX  X XX X  XXXX  XX X X   XX  XXXXX XX XX  XX       XXXXXX   X XX X XXXXXXX  XX",
            "X X  XX X XXX X XXXXXX X  X XXXX X  XXX XX  X  XX X XXX    X XX  X  X XX XXX XXX X       XXX   X     XX X   XX     X XXXX",
            "  X       XX XXX  XXXXXXXXXX X    X   XXXX XXXXX XXX XX X XX XX X  XXX X X     X  XXXXXX XXX  XX  X  XXXXX   X  X XXX  X ",
            "XX XXXX X     XXXX X XXX XX   X X    X XX   XXXX  XXXX XXX  XXX  X   X  XXXX   XXX  XX XXXX X    X XXXX X  XXX     X X XX",
            "     X  XXX X   XXXXX     XXXX XX X XXXXX  X  XX  XXXXX X  XXXX    XX  XX XX  XX  X XXX      XXXX X    X XXXXXXXX X      ",
            "  XX  XX XXXX XXX XX X X  X X   X  X X XX XX X  X X   XXXX  XXXXX    X  X XX XXX  X  XX  X XX   XXXX  X X   X        XX X",
            "X X XX X XX   X  XX X X X XXXXX XXX X  X  XX XX  X XX X XX X      XXX X X    X  X XXX       XXX X     XXX X X   X X X    ",
            "    X X X  XX X   X XX   XX X   X   X X   X X XX X X  XXXX X  XX   XX X  X    X X   X  XXXX XX   X XXXX X    X  X XX XXXX",
            "X  X     XX XX   XXX XXXXXX XXXXX XXXXXXX      X X        X     XX X  XXXXX X X  XXXX X    X XXXX X  X X XX X X XXX XX XX",
            "X    XX  XXXXX XX  XX XX   XXXX  XXXXX  XXX  XXX XX   XX  X X XX X XX XX   X XX  X   XXX     X XX  XX    X  X      XXXXX ",
            "XX X   X XX  X X XX  X   X XXX X XX X XX    XXXX XX  XX X     X   X X    XX    X XXXX XX  XX X  XXX  XX XX X XX   X  X   ",
            "  X  XXXX XXXXX XX XX X  XXXX XXX    XX XXX       X  X X X XXX X  XXXXX XXX X   XX  XX XXXX X    X XXXXXX          X X XX",
            "    XX    XX   XXXXXXX   X  XX  X      XXXXX  XX   X  X X  XXXXXX  XX X  XXX  XX XXXX X       XXXXX    X XXXX X XXX      ",
            "  X XXXXX   X   XXXX X X X  XXXXX  XX XXX X X XXX  X  XXXXXXXXX XX X X XX X  XXXX   XXXXX X  X     X X X XXX    XXXXX XXX",
            "   XX   X X      XXXXX X  XXX   XX X X  XXX     XX XX X X   X X XXXXX   XXX XX XX  XX   X XX    XXXX   X  X    XX   XX   ",
            " X XX X X    X  X XX XXXX X X X X  XXXX  X X  X  X X X  X X XXXX  XX X XXX XX  XX  XX X XXXXX  X X  XXX XX X X  X X X X X",
            "XXX X   X XX XX X   X  XX X X   X  X XX     X   X  X    X   XXX   X  XXXXX XXXXX XX X   X  X XXXX X    X XXXXXXXX   X   X",
            " X XXXXXXX   XXX XX XX X  XXXXXXXXX XX   XX  X  X   XXX XXXXXXX  XXX X X XXX  X X X XXXXX X X XXX    XX  X  XX XXXXXXXXX ",
            "X XX   X XXXXXXX XX X XXXXX  X X      X  XXXX X X X XXXX XXXXX XX  X  X XXXXXX   X  XXXX X XXXXXX    X   X XXX  X     XX ",
            "X XX  XX X  X   XXX XX  XX XXXX  XX XX X      XXX  X   XX X X  XX XX     X  X X XX XX XX XX X    X XXXX         XXX XX XX",
            " XXXX  XXXXX XXXXXXXXX    X      X  X XXXX     X  X  XX   XX      XXXXX X    X X XXX X XXX   XXXXXX    X  XXX XXXX     X ",
            "XX  X XXXX X XXXX  XX XXX    X  XX   XXXXX X X   XXX X X   X X   X   X XX  XXXX  XX   X  XXXXXX X  X     X  X  X XX X XX ",
            "X XXXX X X  X XXX X    X X X   XX  XXXXXX X   X   X    XX X   X  X XXXXX   X X  X  XX  X XXXXXX X  X  X  X   XXX   XXX   ",
            "XXX   X  XX  XX X X XX     XXXXXXX   X  X  XXXXX X XXXXX  X     X X  X  XXXX  X XX      X X XX   X XXXX X    X  X X XX XX",
            "XX         X XXXX X  X XX XX X XXX    XX    X XX XXXXX X X X     X XXXX XXXX XXX XXX X  X  X XXXX XX     XXXX XXX XX   X ",
            "X X   XX X XXX X XX  X   X   XXX    XXXXXXX X XXXXXX  XX  XX  XX XX  X X XXXXX X      X   X XX      X XX X X X  XXXXX X X",
            "XX XXX     XX  X X X X  X XX X  X  XX  XXXX X XXX  XXXXXXX XX  XX  XXXX  XX X XXXXXX   X   XX XXX   X X  X XX      X X   ",
            "XX X XXX  X      X     X   X  XXXXX X XX  XX X X XX X X     XX  XX  XX  X X   X X  XX  X XX X  X    XXX X       X X X   X",
            " X XXX XX  X  X X X  X   X   X   X    X XX    X  X X X  XXXXXX XX    XX  XXXXX X XXX X XX  X XXXX X      XX X XXX      X ",
            "XX XXXXXXX X  XXX  X X X  X  XX XX    XX XXXXX  XXX   XXX   XX X XX  XX X X  XX  X  XXXX  XXX XX   X  X  X X   XXXXX XXXX",
            "X  X X   XXX X XX XX X  X XXXX  X X  X  X  XXX    X  XXXXX X   XXX X  X X XX   X  X X     X  XXX   X X X  XXX  XX   XX   ",
            " X    X  X XX XX  XXXX XXXXXXX  XXXX  XX X  XX    X XXX X  XXX X XXXX  X X XXXXXX   XXXXX X X    X XXXX XX   X  X   XXX X",
            " XX  X     XX X X  X X      XXXX XXXX   XXX XX  XXXX XXX   XXX XX X X    XX  XXX  XX X XX  X  XXX XX   X XXXX XX XXX     ",
            "X X XXXXX  XX XX XX  X   XX   XXXXX  X     X  XX  X  XXXX XX  XXXXX  X        X  X  XXX  XX  X X  X  XX  X  XXXX XXX    X",
            "X XXXX X  X XXXXX X    X XX XXXX X    XXXX    X  X XXXXXX XX XX  XX   XX   X   X X   XX XXXX X  X    XX    X  XX    X X  ",
            "   XX X  X  XXX  XX XXXX   X  X  XXX XX X XXX       X X     XXX XXXX   X XXXX XXX       X X X    X XX XXX    X    X XXXXX",
            "XXXX    XX  XX XXX   X X XX   X  XX  XX  XX X   X XX XXXXX  XX  XX   X  X  XXXXX  XX    X  X  XXX X    X  X X XXX XX    X",
            " X    XX    X XXX X      XX XX XX XX XXXX XXXX XXXX XX X XXX XXXX    XXX XXX X X X  X X   X  XX X    XXXXX XX   XXX  XXXX",
            "XX     XXX  XX   X    X        X  XX   X   X X   XX      XXX X   X X XXXX XX  XX X       X  X      XX XXXX     X X   XX  ",
            " X    XXXXXX X   X     X  XXX         XX   X  XXX X  XX  XXX XXX X  X X X  XXX  X   X    XX X    X  XXX X    X  X X X  XX",
            " XX XX      XXX  X XX XXX X X  X XXXX X XXXX    XX XXXX X X  X  XXXXXXX XXX XXXX XXX X XXX X XXXX X    X XXXXXXXX XX X  X",
            "X  XXXXXX  XX X    XXXXX X  XXXXXXXX   XX   XXXX X    XXXXXXX     X   XX         X  XXXXX X   XXX X  XX     XX  XXXXXXX  ",
            "    X   XX  XXX XX  X  X  X X   XXX   X  X   X XX XXXXXXX   X X XX  XXX XX  XX    X X   X    XX  X XX X XX X    X   X X  ",
            "   XX X X XXX  X X X XXXXXXXX X X   XX  XXXXXXX XXXXX  XX X XXXXXXX  XX  X X X  X  XX X XXX X      XX X XX   X  X X XXXXX",
            "   XX   X X   X XX   X    X X   XXX XX XX  X   X      X X   X   X XXX  XX XX XXX XXXX   X    XXXX X    X XXXX XXX   X  X ",
            "   XXXXXXXX X XXXXXX   XX   XXXXXX XXX  XX XX  X XX   XXXXXXXXX  XX X XXXXXX      X XXXXXXXXX XX  XX    XX  XX  XXXXXXX X",
            "X    X  XXXXX XXXXXX  XX XX X X   XXXXXX  X X XX  XXXXX X XX  XXX XXX XX    X X   X   XX XXX  XXX  XX X  X  XX X XX  X   ",
            "   X  X X  XX X XXX X   XXXXXX  X X X  XXXX XX X X     XX   XXX      X X X X    X  XXX X XX X  X X XXXX X    X XX    X XX",
            "XXXXX   XX  XXX    X   X X  X X X  X X  X X  XX  XXX XXXXXXXXX  XXXX  X X  X XXX  XXXX   X X XXXX XX   X  XXXXX XXX X    ",
            "XX XX XX XX  X X  X XXX       XXX  X        X  X   XX XX     X X X   X    XXX    X XXX XX X XXXXXX  XXX     X  XXXX  XXX ",
            "XX   X   X XXX XXX XXXX   X XXXXX XX   X XXX  XXXX  XXXX XX  X X X   XX  XXX X XXX X XXX  XXX   XX   XX  XXXXXX  XX    X ",
            "    X XXXXX XX  XX X X  XXXXXX  XX  XX   XX XX  X XX X X      X   X XX  XX XX   X  XX  X XX X  X X XX X X  X X X    XX XX",
            "XXX XX XX X XXX X   XXX XXXX XX XXX XXX XXXX X    X   XXXXXX   X   X X   XXXXX X XXXX   X  X  XXXXX    X XXXX XX X  XX XX",
            "  XXX X  XX  XX X XXX  X    XXX XXXX XXX    X XXX X   X XXX     X   XX     XXXX   XXX  XX XXXX  XX XX XX X  X  XXX X XX X",
            " X  X    XX X XXXX   X  X XX  X  X X X X  X  XXX XX     X    X X     XXXXX X X   XXX  X   X  X XX   XXXX  X XXX  XXX XXX ",
            " XX X XXXX XXXXXXX X X    X   XX X XX XX X  XXX        X XXXXX    XXX XXX XX   XX  XXX X XXXX    X  XXX X      X X  X  XX",
            " X      XX  X  XXX     X XXXX   XX   X X XXXX   X    XX   X  XXXXX  X XXX XXX XX XXXXX     X  XXX X  X X XXXX X   X X   X",
            "   X  X  XX   X X XX  X    X  X X XXX  X    X  XX     X  X X XXXXXX  X     XXX  XX XX  XXXX   XXXX X  XX XXXX  XXX X XXXX",
            "XX X X XXX X    X X XXX   XX   X X X  XXXXXX   X  X X   X  X X   XXXXX  XX X X XX     X   X   X       X X  X X   XXXX XX ",
            "    X XX XX   X    X X X XXX XXXXX   XXX  X  X XX    X  X  X XXXXX X  X X XXXXX X  XXX X  XXX      XXXX X           X XXX",
            "X X        XXX XX  X XX XX    X XXX X XXX X  XXXXXX   X        XXXXXXX X  XXXXX  XX  XX X  X XXXX X      XXXX XXX X X  XX",
            "   XXXX  X     X  X X        XX XXX      XXX   X     XX  XXXX  X X  X    X   XXXX   X   X XX X X   X  XXXXX  X XXX    XXX",
            " X X X XXXXXXX XX   XXX XX   XXX X  XXXX  XXX X X XXX X XXX  XXX  X  X XXXX XX XXX    X  X X  XX  X XX XX   X    XXX X   ",
            "     XXX X  XX   X  XXX XX  X  X  X    X   X    XX    XXXXXX XXXXXX  X X XX X  XX  XXX X XX X    X XXXX X  X X     X X  X",
            "XX XXX X X   X   X X X X  X     XXXX XXX X X   X  X X  XX  X XXXX   X  XX     XX XX XXXX     XX X X    X XXXX XX XX X    ",
            "XXXXX X X   XXX X  XXX  XXX     X XX  XXXXX   X X X  XXXXXX XXX   XXX XXX   XX XXX XXX XX  XX  X X X XX  X  X  XX XX  X X",
            "XX  X  XX    X XX  X   XXXXX  X   X  XXXX  XXXXX  X  XXXXXXXX X   XXXXXXX   XX XXXX  XX  XX     XXXX  X X X XXX  XX  X   ",
            "   X XX  XX X       XXXXX  X X    XXX XXXX  XXX   XX XX     X      X    X  X XXXX  XX  X XX X       X X X  X X X     X  X",
            " XX XX XX    XXX  XX X X X X XX  XX     XX XXX XXX X XXXX   X X X  XXX XXX XXX X XX XXXXXX    XXX X    X XXXX XX X  X  XX",
            "X   XXXXXXX   X XXX X   X   XXXXX   X X X XX X  X X XXXXXXXXXXXX  X  X X X  XXXX X XXXXXX  X    X   X    XX  XX XXXXXXXXX",
            "X XXX   X X  X XXXX    XX  XX   XXX XX XX  XXX  XX    X X   X     X X X XX XXXX X X X   XX  XX  X  X  X XX X    X   XX   ",
            "   XX X XX XXXXX   X  XXXX XX X X XX X X   X   X  X X   X X X X    XXXXXXXXXXX  XX  X X X X X    X XXXX X    X  X X XX  X",
            "X   X   X  XX XX   X  XX  X X   X   X X   X XX XX XX  XXX   XX   XXX   XX XXX  X XXXX   X  X XXXXXX    X XX X XXX   X   X",
            "X XXXXXXX  XX     XX  X X X XXXXX XX  XXX X   X XXXX XXXXXXXXXXX X  XXX   XXXXX  X XXXXXX X  X X X  XXX  XX XXX XXXXX XXX",
            " X XXX X    X   XX XXX     X X   XX XXX    XX   XX X  X X XXX       X XXX    XXX XX    XX X     XX   XX  X XX XX         ",
            " XXX  XXXXX  XX   X XXXX X  XX X  XX XX   X X    XXXX   X  X XXX X  XXXX X XX  XXX  X X  XXX     X  XXX X  X X    XX X XX",
            "X X    XXXXXX  X XX  XX XX X XX  XXXXXXX     X X X      X X  XX XX   XXX    XXXX XX XXXX   X  XXX X    X XXXX X X   XX  X",
            " X X XXX    X XXX XXX  XXXXXX X XX XXX XXX   XXXXXX X XX X    X XX XXX   X XXX X   XX XX X    X XX X  XX    X XX  X XXX X",
            "  X     X  XX XX X     XX X     X   X XXXXXX  X X X XX  XXX  XX XXXXX    XX X XX  X  X XXX   XX X  X XXX     X X XXX     ",
            "XXX  XX X X   XX X  X  X X    XX XX  XX XX  XXX X XX X    X  XXXX  X XX  XXXXX  X    XX  XXXXX   X XXXXXX    X XXXXX   XX",
            "XXX XX XX XXX    X XX     XX XX XX  XXXX XXXXXXXXXX XX X  X  XX XX XX  X  XX   X XX X   X  X XXXX XX   X XX XXX XX      X",
            "  X XXX  X X  X X   X   X X   X   X X X XX  XXX         XX  X XXXX    XX     XXX   X XX XXX  X  XXXXX X   X    XX XXX X  ",
            "     X XXXX   XXX  X  X  XX X XXX X  XX XXX XX XX    XXXX   X XX X XXX  XX XXX       X  XXX    XX XX     X XX XXX  X     ",
            "XXX  XX XX XX   XXXX X      XX X XXX   X  X X X  X XXXX XX   XXXX   X XX XXX XX X  X  X   X X    X XX X XX   X X  XXXX XX",
            " X XXX XX  XX X  X          XXXX X  X  XX X X  XX X  XXX  X XXXX    X  XX   X XX  X XX     X  X X X    X XXXXXX X  XX    ",
            "XX   XXXXXXX XX X  XXXXXXX      X  XXXXX X  XXX    X  X   XX X XXX  X  XX  XX XXX  X X   X    X    X   XX   X  XXXX XXXX ",
            "X   X       XX XXXXX       X   XX  X X XXXXXXXX   XXXXX  X XX X XXX XXXXXXX X    X   X XXX  X X X  X XX        X  XX     ",
            "XXX X X      X X XX  X XXX      XXX X X XX X  XXX X X  X   XX  X   XX    XX X XXX    XXX  XXX    X XXXXXX  X X   XX  X  X",
            "  XXX   XX XXXX X XX XXX  X X XXX   X   X XX   X XXXXXXX   XX X  XX   X  X X   X XXXXX X   X  XXX XX   X XXXXXX X    X   ",
            "XX   XXXXX XX XX  X X XX X  X X X   XX XX    XX X   XXX X  XX XX  X X X XXX XXXXX  XXXXX   X   XXX    XXXX   X XX X XXX X",
            "  X  X XX   X X XXXX   XX XXXX   X XX X  XX  X   X X  XX   X  XX  XXX X X  X  X     XX XXXXX X   XX   XXXX X  X X XX     ",
            "XXX   XX X  XX  XXX  X XX X   X XX  X X     X   XXX XX  XXXXX     XX XX  X  X XXX  X  XX XX XX X X XXXXXX      XXXXXX  XX",
            "X XXXX   XXXXXX XX X  XX  X X  X X  X  X XXXXXXXX X XXXX XXX X  X XXXX XX    XXX  X XX X X X XXXX XX   X XX X X XX X X XX",
            "X   X X  X XXX X XX    XX X X  XX    XXX   XX X   XXX    XX XXX  XX XXXXX  X X  XX XX   XXXX    X  X  X   XX   X    XXX  ",
            "X   X  X  X X X    X   XXX   X  X  XXXX X X      X X   XX X  XX XXXX XXXXXXXXX      X  XXX X    X     X   X X  X XXX  XX ",
            "XX X XXXXXX     XXX X  X XX XXXXXXX X XX XX          X  XXX X    XX  X   XXXX XXX  XX X   X X  X X XXXX X    X X XXX  XXX",
            "X XXXX   XX  XX  X  XX XX  X    XXXX      X  XX   X XX X X  XX    XXX   XX    XX XX    X   X XX X XX   X  X XXX     X    ",
            " XXX  X  X    X     X XXX  XXXXXX   X X XXXXX XXXX    XXXXXXXX    XX XX  X  XX X   XXXXXX X XX X XX X XXX   XX XXXXXX X X",
            "        X  XXXX XXXXXXXX XXXX   XXXXXXXXXXX    XXX X XX X   XXX X XXX  XX XX XXX X XX   X X    X XX  XXX   XX  XX   XXX  ",
            "XXXXXXX   XX XX  XXX   X X  X X XX  XX  XX    X X XXX  XX X X   X   X XX  XXXXX X   X X XXXXX    X XXXXXXX   X  X X XX XX",
            "X     X  X X     X   X    XXX   XX X  X  X X  X XXX    XX   X X     X  X X XX  X XX X   XX X XXXX XX   X XX XXX X   X  XX",
            "X XXX X XX X  X  XX X X X  XXXXXX    X XX X     XX   XX XXXXXXXX  X X   X           XXXXXXXX   XX          X X  XXXXXXX  ",
            "X XXX X XX X  XX XX XX  X  X   XXX X  XX    X  XXX XX X X XX  XX  XX XXXX XX X  X   XX XX   XX    X  XX  X  XX XX XX X  X",
            "X XXX X XXXXXXX XXXXXX   X   XXX X X X XXX XXXXX X    XXXXXX X XXXXXX   X     X XX X X XXXX X       XXX X    X    XX X  X",
            "X     X  XX X XXX  X X XX  X  X XXX XXX X X XXX XXXXXX X    X X X  X XX X X   XX XXXXXXX     XXXX X    X XXXXXX  XX     X",
            "XXXXXXX       X X  X   X  X   X  XX  XXXX  X   X  X XX  X    X   X   X   XXXXX X X  X  X X X       XX XX XXX XXXXX   XXXX"
        };

        private static readonly List<QrSegment> Segment10 = QrSegment.MakeSegments("https://www.nayuki.io/");
        private static readonly string[] Modules10 = {
            "XXXXXXX  X  XXX X XX  XXXXXXX",
            "X     X XXXXX XXXX  X X     X",
            "X XXX X    XX XX XXXX X XXX X",
            "X XXX X  X  X XX   XX X XXX X",
            "X XXX X   XXX  X  X   X XXX X",
            "X     X X X     X XX  X     X",
            "XXXXXXX X X X X X X X XXXXXXX",
            "        X X X XXXXXXX        ",
            "    XXXX  X X X   XXX XX   X ",
            "X XXX  X X XX  X X XX X XXXXX",
            "XX  XXXX X XX   X   XX   X  X",
            " X   X  X  X X X X XXX XXX XX",
            " X XX X XX XX X   X    X    X",
            " XXXXX   X  XXXX XX   X X X X",
            "   XX XX  XXXXXX    X   X   X",
            "XX     X  X  X     XXX X X X ",
            " XXX XX XX    XX X XXX     XX",
            "XXX XX  XX XX    XX X XXXX  X",
            "  X XXXX     X      X   XX  X",
            "  XXXX  X  X XX XX XX  XXX X ",
            "XXX XXXX  XXX  XX   XXXXX  X ",
            "        X  X  XX    X   X X X",
            "XXXXXXX XXX XX   X XX X X   X",
            "X     X XXXX X  X  XX   XX X ",
            "X XXX X XX     XXXXXXXXXX  XX",
            "X XXX X  X  XX   XX    X  XX ",
            "X XXX X  X XX   XXXXXX   X XX",
            "X     X    X   X XX XX X X XX",
            "XXXXXXX  X  XXX  X  XX  XX X "
        };

        private static readonly List<QrSegment> Segment11 = QrSegment.MakeSegments("維基百科（Wikipedia，聆聽i/ˌwɪkᵻˈpiːdi.ə/）是一個自由內容、公開編輯且多語言的網路百科全書協作計畫");
        private static readonly string[] Modules11 = {
            "XXXXXXX      X X    XXXXXX XX  X X  X XXXXXXX",
            "X     X XX    X  X    X   XXX X  X X  X     X",
            "X XXX X        X  X XXXX  X   X    X  X XXX X",
            "X XXX X XX    XXX  XX X  X XX X XX XX X XXX X",
            "X XXX X  XX X   X X XXXXX X XX    XXX X XXX X",
            "X     X XX X XX X  XX   XXX     X     X     X",
            "XXXXXXX X X X X X X X X X X X X X X X XXXXXXX",
            "          X   XXX XXX   X XXXXX  XXXX        ",
            "XXXXX XXX X XXXX   XXXXXXXXXX   X    X X X X ",
            " X X X XX X     X XXXX XXXX  X     XX X X X X",
            "X   X XX X   X XX   XX    XXX   X XX X   X XX",
            " X     X XXX XX XXXXX    XXXXXX XXX   XX   X ",
            " XX XXX  X XX XX X   XXXX X XX  XX   XXXX XXX",
            "X XX X XX XX  XXX  XXXX XXX X    XXX XXXXXX X",
            " X XX XXXX XX  X    XX X  X XXX X  X  X  XXXX",
            " X         XXX X  XXX XXX  X    XX X   XX  X ",
            "XXX   XXXXXXX    X XXXX  X  X XXXX   X XXXX X",
            " X   X  X    X X   XX     X X      XXXX X X X",
            "     XX X   X X  XXX X X XX   XXXXXXX X   X X",
            "         XXXX XX    X   XX XX   X    X      X",
            "XXXXXXXXX  XXXXX   XXXXXXXXXX  XXX  XXXXX XX ",
            "XXX X   XXXX  XXXXX X   X X X   X XXX   XX XX",
            " XXXX X XXX  XX  XXXX X X X   XXXXX X X XX  X",
            "  X X   X X   X  X XX   XX  X X    XX   X   X",
            "X   XXXXXX XXXXX    XXXXXX   XX X   XXXXXX XX",
            " X XXX X  X X   XXXX XX   XX         XXXX XXX",
            "    XXX   XXXX XX   X    XX XX XXXXXX X  XX X",
            " X     X  X XXX X X    XXX  XXXX   X XXXXX XX",
            "X XX XX       XXX  XXXX XXXXX X X    XXXX  X ",
            "XXX XX X  X  X  X  X X  X XX X  XXXX XX X   X",
            "  XX XXX XXXX  X XXX XX  X XX   XXX   XXX   X",
            "XX X X  XX XXX X XX X     XX X XX  XXXX XX X ",
            "XXX   X X X X       XX XXXXXXXX XX XXX XX  X ",
            " XXX X  X XX X X     XXXXXX XXXXX   XXX XXX X",
            "    X X XX   X   X XX XX   XX  XXXXX  XX XXXX",
            " XXXX  XX XX   X X     XX  XXXX X     X X    ",
            "X  XX XX    X XX X XXXXXXX  XX  XX  XXXXX XXX",
            "        X X  XXXX   X   XXXXX    XX X   XXX X",
            "XXXXXXX XXXXXXXX   XX X X XX X  X   X X XX XX",
            "X     X  XXXX XXXX XX   X XX    XXX X   X  XX",
            "X XXX X X  XXXXX  XXXXXXXXX XXXXX  XXXXXXXXX ",
            "X XXX X XX  X   X X  XX X X X XX     XX XXX  ",
            "X XXX X XXXXX  XXXXX        X    XXX   XXXX X",
            "X     X XXX XX  X X   X XX  XXX XXX X X      ",
            "XXXXXXX XXX  XX X  XXXX  X XX  XXXX    XX  X "
        };

        private static readonly List<QrSegment> Segment12 = new List<QrSegment> { QrSegment.MakeNumeric(""), QrSegment.MakeAlphanumeric("") };
        private static readonly string[] Modules12 = {
            "XXXXXXX  X    XXXXXXX",
            "X     X   XX  X     X",
            "X XXX X   XXX X XXX X",
            "X XXX X   X   X XXX X",
            "X XXX X X X   X XXX X",
            "X     X  XX X X     X",
            "XXXXXXX X X X XXXXXXX",
            "        X XX         ",
            "  XX  XXX X XXX X    ",
            "  X X  XX X  XXX  X  ",
            "X X   XXXX  X XXXX  X",
            "XXXXX    XX        X ",
            " X XX X XXX X X X X X",
            "        X  X   X  X X",
            "XXXXXXX X       X XX ",
            "X     X    XX X  X   ",
            "X XXX X  XXXXX   X  X",
            "X XXX X X X XXX X  X ",
            "X XXX X XXXX  X XXX  ",
            "X     X       X XX XX",
            "XXXXXXX    XXX X X X "
        };

        private static readonly List<QrSegment> Segment13 = new List<QrSegment> { QrSegmentAdvanced.MakeKanji("昨夜のコンサートは最高でした。") };
        private static readonly string[] Modules13 = {
            "XXXXXXX  XXX   X  XXXXXXX",
            "X     X  X X  X   X     X",
            "X XXX X X X X     X XXX X",
            "X XXX X X   X  XX X XXX X",
            "X XXX X XXX X XXX X XXX X",
            "X     X XXX   XXX X     X",
            "XXXXXXX X X X X X XXXXXXX",
            "        XXXX   X         ",
            "X XXXXX  X    XX  XXXXX  ",
            " X  X  X  XXX X XXXX XXXX",
            "  XX XX XXXX   X  X XXX X",
            "  XX X XXX   X    XX    X",
            "X XX  X   X X     X  X XX",
            "XX  X  XXX   XX X X XX  X",
            "X     XXX XXXX X  XX XX  ",
            "X  XX   XXXX X   X  XXXXX",
            "X XXXXX XX XX   XXXXX  X ",
            "        X X X  XX   XXX X",
            "XXXXXXX  XX X XXX X XX XX",
            "X     X X X XX XX   XX X ",
            "X XXX X X   XXXXXXXXX  X ",
            "X XXX X XXX   X XXX XXX X",
            "X XXX X XXX X X    XX   X",
            "X     X  XX X  XX X  X  X",
            "XXXXXXX X   X  XXXX  XX  "
        };

        private static readonly List<QrSegment> Segment14 = QrSegmentAdvanced.MakeSegmentsOptimally("2342342340ABC234234jkl~~", Ecc.High);
        private static readonly string[] Modules14 = {
            "XXXXXXX X  X X        XXXXXXX",
            "X     X X  XXXX  XX X X     X",
            "X XXX X X XXXXXX XX   X XXX X",
            "X XXX X  XX  X X X    X XXX X",
            "X XXX X   XXX XXXXX X X XXX X",
            "X     X XX XXX X X X  X     X",
            "XXXXXXX X X X X X X X XXXXXXX",
            "        XX   XXXXXXX         ",
            "  XXX X X X XX X     XXX  XXX",
            "XX X X XXX XX    XX X XX  XXX",
            "  XX XX XXX   XXXX X    X XXX",
            "XX  XX X  XX X   X XXX X XXXX",
            "XXX X XX    XX   XXX XX XX  X",
            "XXX XX X X XX X   XX    X  X ",
            "     XX X  X X  X     X  XXX ",
            "  XXXX XXX X    XXX XX  X XX ",
            "XX XX XX XXXXXXXX  XXX X  XXX",
            "XX   X XX XXXX XXXX  X X X X ",
            "X  X XXXX  XX  XXX  X X X  XX",
            "X  X    X   XX X     X   XXXX",
            "X X XXX X XXXXXXXXX XXXXXX X ",
            "        X  XX  X XXXX   X XX ",
            "XXXXXXX  X   X X  XXX X X  XX",
            "X     X   XX   X XX X   XXXX ",
            "X XXX X X  X X X  X XXXXX XXX",
            "X XXX X XX  XXX  X    X XX X ",
            "X XXX X XXX  XXXXXXX    X XX ",
            "X     X  XX XXXX  X   X  XX  ",
            "XXXXXXX    XX X X XXXXX  X X "
        };

        private static readonly QrCodeTestCase[] TestCases = new QrCodeTestCase[] {
            new QrCodeTestCase(1, Segment1, Ecc.Medium, Modules1, Ecc.High, 4),
            new QrCodeTestCase(2, Segment2, Ecc.Medium, Modules2, Ecc.Medium, 2),
            new QrCodeTestCase(3, Segment3, Ecc.Medium, Modules3, Ecc.Quartile, 2),
            new QrCodeTestCase(4, Segment4, Ecc.Medium, Modules4, Ecc.High, 1),
            new QrCodeTestCase(5, Segment5, Ecc.Medium, Modules5, Ecc.Medium, 4),
            new QrCodeTestCase(6, Segment6, Ecc.High, Modules6, Ecc.High, 6),
            new QrCodeTestCase(7, Segment7, Ecc.Low, Modules7, Ecc.Medium, 1),
            new QrCodeTestCase(8, Segment8, Ecc.Quartile, Modules8, Ecc.Quartile, 6),
            new QrCodeTestCase(9, Segment9, Ecc.High, Modules9, Ecc.High, 2),
            new QrCodeTestCase(10, Segment10, Ecc.Quartile, Modules10, Ecc.High, 4),
            new QrCodeTestCase(11, Segment11, Ecc.Low, Modules11, Ecc.Low, 2),
            new QrCodeTestCase(12, Segment12, Ecc.Medium, Modules12, Ecc.High, 3),
            new QrCodeTestCase(13, Segment13, Ecc.Medium, Modules13, Ecc.Medium, 2),
            new QrCodeTestCase(14, Segment14, Ecc.High, Modules14, Ecc.High, 2)
        };

        public IEnumerator<object[]> GetEnumerator()
        {
            foreach (var testCase in TestCases)
            {
                yield return new object[] { testCase };
            }
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
}
